#!/usr/bin/env python3
"""The Ultimate boot screen (a Plymouth script theme), in the Cognition style.

    make-plymouth.py OUTDIR MARK_PNG

writes OUTDIR/ultimate.plymouth, ultimate.script and the images it uses:
the network as a still backdrop (bg.png), pulses that travel along its
edges, the Ultimate Linux mark (MARK_PNG, rendered from logos/) with a
breathing glow, and the linked progress nodes of the login splash, so
boot, login and desktop read as one piece.

Drawn with Pillow; the edges the pulses travel are written into the script.
"""

import math
import os
import random
import shutil
import sys

from PIL import Image, ImageDraw, ImageFilter

W, H = 1920, 1080
VOID = (3, 6, 5)
DIM = (13, 59, 40)
MID = (0, 199, 122)
MINT = (0, 255, 156)
TEXT = (207, 232, 214)
QUIET = (111, 138, 122)
RAISED = (22, 34, 28)
LAYERS, PER = 9, 8


def lattice(seed=7):
    """Nodes in layers, left to right, and edges between neighbouring layers
    -- the wallpaper's shape."""
    rnd = random.Random(seed)
    nodes, edges = [], []
    for li in range(LAYERS):
        x = 0.06 + 0.88 * li / (LAYERS - 1)
        for k in range(PER):
            y = 0.1 + 0.8 * (k + 0.5) / PER + rnd.uniform(-0.035, 0.035)
            nodes.append((x + rnd.uniform(-0.02, 0.02), y))
    for li in range(LAYERS - 1):
        for k in range(PER):
            a = li * PER + k
            near = [j for j in (k - 1, k, k + 1) if 0 <= j < PER]   # neighbours, like the wallpaper
            for j in rnd.sample(near, min(2, len(near))):
                edges.append((a, (li + 1) * PER + j))
    return nodes, edges


def backdrop(nodes, edges, out):
    img = Image.new("RGB", (W, H), VOID)
    # a faint vertical wash, lighter towards the right like the wallpaper
    wash = Image.new("RGB", (W, H))
    wd = ImageDraw.Draw(wash)
    for x in range(W):
        t = x / W
        wd.line([(x, 0), (x, H)], fill=(int(3 + 4 * t), int(6 + 14 * t), int(5 + 10 * t)))
    img = Image.blend(img, wash, 0.9)
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    px = [(x * W, y * H) for x, y in nodes]
    for a, b in edges:
        d.line([px[a], px[b]], fill=(18, 84, 58, 190), width=2)
    for x, y in px:
        d.ellipse([x - 3, y - 3, x + 3, y + 3], fill=MID + (170,))
    img.paste(layer, (0, 0), layer)
    # the pool of darkness the mark sits in
    pool = Image.new("L", (W, H), 0)
    ImageDraw.Draw(pool).ellipse([W / 2 - 560, H / 2 - 520, W / 2 + 560, H / 2 + 520], fill=235)
    pool = pool.filter(ImageFilter.GaussianBlur(170))
    img.paste(Image.new("RGB", (W, H), VOID), (0, 0), pool)
    img.save(os.path.join(out, "bg.png"))


def dot(path, r, color, glow=0):
    size = int((r + glow) * 2 + 4)
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    c = size / 2
    if glow:
        g = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        ImageDraw.Draw(g).ellipse([c - r - glow / 2, c - r - glow / 2, c + r + glow / 2, c + r + glow / 2],
                                  fill=color + (150,))
        img = Image.alpha_composite(img, g.filter(ImageFilter.GaussianBlur(glow / 2.5)))
    ImageDraw.Draw(img).ellipse([c - r, c - r, c + r, c + r], fill=color + (255,))
    img.save(path)


def ring(path, r, color):
    size = int(r * 2 + 4)
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    c = size / 2
    ImageDraw.Draw(img).ellipse([c - r, c - r, c + r, c + r], fill=RAISED + (255,), outline=color + (255,), width=2)
    img.save(path)


def bar(path, w, h, color):
    Image.new("RGBA", (w, h), color + (255,)).save(path)


def halo(path, size=520):
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ImageDraw.Draw(img).ellipse([size * 0.3, size * 0.3, size * 0.7, size * 0.7], fill=MINT + (110,))
    img.filter(ImageFilter.GaussianBlur(size * 0.11)).save(path)


SCRIPT = r'''# The Ultimate boot screen -- generated by make-plymouth.py; edit that.
# The network behind, pulses travelling its edges, the mark breathing in
# the middle, and one linked node per stretch of the boot.

W = Window.GetWidth(0); H = Window.GetHeight(0);
if (!W) { W = Window.GetWidth(); H = Window.GetHeight(); }
Window.SetBackgroundTopColor(0.012, 0.024, 0.02);
Window.SetBackgroundBottomColor(0.012, 0.024, 0.02);

# the backdrop covers the screen, cropped to keep its shape
bgi = Image("bg.png");
k = Math.Max(W / bgi.GetWidth(), H / bgi.GetHeight());
bgw = bgi.GetWidth() * k; bgh = bgi.GetHeight() * k;
bg = Sprite(bgi.Scale(bgw, bgh));
bgx = (W - bgw) / 2; bgy = (H - bgh) / 2;
bg.SetPosition(bgx, bgy, -10);

# the mark, a fifth of the short side, with its halo
side = Math.Min(W, H);
ms = Math.Int(side * 0.2);
mark = Sprite(Image("mark.png").Scale(ms, ms));
mx = W / 2 - ms / 2; my = H / 2 - ms * 0.95;
mark.SetPosition(mx, my, 10);
hs = Math.Int(ms * 2.2);
halo = Sprite(Image("halo.png").Scale(hs, hs));
halo.SetPosition(W / 2 - hs / 2, my + ms / 2 - hs / 2, 5);

# the name: a small "RedCyfer's" above the spaced title
by = Sprite(Image.Text("R E D C Y F E R ' S", 0.60, 0.72, 0.64, 1, "Inter " + Math.Int(ms * 0.065)));
by.SetPosition(W / 2 - by.GetImage().GetWidth() / 2, my + ms * 1.12, 10);
ty = my + ms * 1.12 + by.GetImage().GetHeight() + ms * 0.03;
title = Sprite(Image.Text("U  L  T  I  M  A  T  E     L  I  N  U  X", 0.81, 0.91, 0.84, 1, "Inter Light " + Math.Int(ms * 0.13)));
title.SetPosition(W / 2 - title.GetImage().GetWidth() / 2, ty, 10);

# progress: six linked nodes
N = 6;
gap = Math.Int(ms * 0.22);
py = ty + title.GetImage().GetHeight() + ms * 0.2;
px0 = W / 2 - gap * (N - 1) / 2;
on = Image("dot-on.png"); off = Image("dot-off.png");
lon = Image("link-on.png").Scale(gap, 3); loff = Image("link-off.png").Scale(gap, 3);
for (i = 0; i < N; i++) {
  d[i] = Sprite(off);
  d[i].SetPosition(px0 + i * gap - off.GetWidth() / 2, py - off.GetHeight() / 2, 12);
  if (i < N - 1) {
    l[i] = Sprite(loff);
    l[i].SetPosition(px0 + i * gap, py - 1, 11);
  }
}
lit = 0;

mode = Plymouth.GetMode();
if (mode == "shutdown") status_text = "shutting down";
else if (mode == "reboot") status_text = "restarting";
else status_text = "starting";
fun set_status(t) {
  global.status = Sprite(Image.Text(t, 0.44, 0.54, 0.48, 1, "JetBrains Mono " + Math.Int(ms * 0.075)));
  global.status.SetPosition(W / 2 - global.status.GetImage().GetWidth() / 2, py + ms * 0.16, 12);
}
set_status(status_text);

fun progress_cb(duration, progress) {
  n = Math.Int(progress * N + 0.5);
  if (n > N) n = N;
  while (global.lit < n) {
    i = global.lit;
    d[i].SetImage(on);
    d[i].SetPosition(px0 + i * gap - on.GetWidth() / 2, py - on.GetHeight() / 2, 12);
    if (i > 0) l[i - 1].SetImage(lon);
    global.lit++;
  }
}
Plymouth.SetBootProgressFunction(progress_cb);

# pulses: bright points travelling along the network's edges
@EDGES@
pulse = Image("pulse.png");
P = 7;
for (i = 0; i < P; i++) {
  ps[i] = Sprite(pulse);
  pe[i] = Math.Int(Math.Random() * NE);
  pt[i] = Math.Random();
  pv[i] = 0.006 + Math.Random() * 0.008;
}
t = 0;
fun refresh_cb() {
  global.t++;
  # the halo breathes (about 3 s a breath)
  halo.SetOpacity(0.55 + 0.35 * Math.Sin(global.t / 50 * 3.14159 / 1.5));
  for (i = 0; i < P; i++) {
    pt[i] += pv[i];
    if (pt[i] >= 1) { pt[i] = 0; pe[i] = Math.Int(Math.Random() * NE); }
    e = pe[i];
    x = bgx + (ex0[e] + (ex1[e] - ex0[e]) * pt[i]) * bgw;
    y = bgy + (ey0[e] + (ey1[e] - ey0[e]) * pt[i]) * bgh;
    ps[i].SetPosition(x - pulse.GetWidth() / 2, y - pulse.GetHeight() / 2, -5);
    ps[i].SetOpacity(Math.Sin(pt[i] * 3.14159));
  }
}
Plymouth.SetRefreshFunction(refresh_cb);

# messages (a disk check, say) replace the status line
fun message_cb(text) { set_status(text); }
Plymouth.SetMessageFunction(message_cb);

# a password prompt (an encrypted disk): the question and one node per key
fun password_cb(prompt, bullets) {
  global.ask = Sprite(Image.Text(prompt, 0.81, 0.91, 0.84, 1, "Inter " + Math.Int(ms * 0.08)));
  global.ask.SetPosition(W / 2 - global.ask.GetImage().GetWidth() / 2, py + ms * 0.4, 20);
  for (i = 0; i < 32; i++) {
    if (!global.b[i]) global.b[i] = Sprite(on);
    global.b[i].SetOpacity(i < bullets);
    global.b[i].SetPosition(W / 2 + (i - bullets / 2) * on.GetWidth() * 1.6, py + ms * 0.62, 20);
  }
}
fun normal_cb() {
  if (global.ask) global.ask.SetOpacity(0);
  for (i = 0; i < 32; i++) if (global.b[i]) global.b[i].SetOpacity(0);
}
Plymouth.SetDisplayPasswordFunction(password_cb);
Plymouth.SetDisplayNormalFunction(normal_cb);

fun quit_cb() { progress_cb(0, 1); }
Plymouth.SetQuitFunction(quit_cb);
'''

PLYMOUTH = """[Plymouth Theme]
Name=Ultimate
Description=The Cognition network behind the RedCyfer's Ultimate Linux mark
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/ultimate
ScriptFile=/usr/share/plymouth/themes/ultimate/ultimate.script
"""


def main(out, mark_png):
    os.makedirs(out, exist_ok=True)
    nodes, edges = lattice()
    backdrop(nodes, edges, out)
    shutil.copy(mark_png, os.path.join(out, "mark.png"))
    halo(os.path.join(out, "halo.png"))
    dot(os.path.join(out, "dot-on.png"), 8, MINT, glow=10)
    ring(os.path.join(out, "dot-off.png"), 7, (34, 50, 42))
    bar(os.path.join(out, "link-on.png"), 8, 3, MID)
    bar(os.path.join(out, "link-off.png"), 8, 3, RAISED)
    dot(os.path.join(out, "pulse.png"), 3, (220, 255, 240), glow=12)
    arr = [f"NE = {len(edges)};"]
    for i, (a, b) in enumerate(edges):
        (x0, y0), (x1, y1) = nodes[a], nodes[b]
        arr.append(f"ex0[{i}] = {x0:.4f}; ey0[{i}] = {y0:.4f}; ex1[{i}] = {x1:.4f}; ey1[{i}] = {y1:.4f};")
    with open(os.path.join(out, "ultimate.script"), "w") as fh:
        fh.write(SCRIPT.replace("@EDGES@", "\n".join(arr)))
    with open(os.path.join(out, "ultimate.plymouth"), "w") as fh:
        fh.write(PLYMOUTH)
    print("wrote the Ultimate Plymouth theme to", out)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
