#!/usr/bin/env python3
"""Which BLFS build step installed each file of the desktop layer.

The BLFS scripts installed straight into the system, one package at a time,
so a file's change time (ctime) falls inside the window of the build that
last wrote it. Windows come from the build's own records:
  * /blfs/timings.tsv  exact start/end of every attempt (newer builds);
  * otherwise a log's birth time to its last write, starting at the driver's
    own "== [n/N] name HH:MM" line when the package was retried.

Run inside a container with the build tree at /b (read-only):
    attribute.py /b <driver-logs-dir> <out.json>

Writes {"packages": {id: [paths]}, "unattributed": [...], "overlaps": [...],
"windows": {...}} and prints a summary. Files already owned by a pacman
package are left out of "packages" and listed in "overlaps" when a BLFS
build rewrote them. Generated caches and account files are skipped (their
owners are pacman hooks and install scripts).
"""
import datetime as dt, glob, json, os, re, stat, sys
root, logdir, out = sys.argv[1], sys.argv[2], sys.argv[3]
utc = dt.timezone.utc
SLACK = 90   # seconds after a log's last write still counted to it

SKIP_TREES = ["/proc", "/sys", "/dev", "/run", "/tmp", "/sources", "/jhalfs",
              "/tools", "/blfs", "/var/lib/pacman", "/var/cache", "/home",
              "/root", "/var/log", "/var/tmp", "/lost+found", "/mnt", "/media",
              "/var/lib/systemd", "/var/lib/sddm", "/srv", "/boot/grub"]
# generated by triggers (pacman hooks regenerate them), or per-machine
SKIP_FILES = re.compile(r"""^(
   /etc/(passwd|group|shadow|gshadow|subuid|subgid)(-)?$
 | /etc/(ld\.so\.cache|machine-id|resolv\.conf|hostname|fstab|shells|adjtime|localtime|mtab)$
 | /etc/ssl/certs/.*
 | /usr/share/info/dir$
 | .*/icon-theme\.cache$
 | .*/gschemas\.compiled$
 | .*/giomodule\.cache$
 | .*/loaders\.cache$
 | .*/immodules\.cache$
 | /usr/share/applications/mimeinfo\.cache$
 | /usr/share/mime/(?!packages/).*
 | .*/fonts\.(dir|scale)$
 | .*/fonts\.cache-\d+$
 | /usr/lib/modules/[^/]+/modules\..*
 | /lib/modules/[^/]+/modules\..*
 | .*/hwdb\.bin$
 | /usr/lib/locale/locale-archive$
 | /var/lib/dbus/machine-id$
 | .*/__pycache__/.*\.pyc$
)""", re.X)

# Which services a machine enables (systemctl enable's links, aliases such as
# display-manager.service) is the machine's state, not a package's content.
ENABLEMENT = re.compile(r"^/etc/systemd/(system|user)/")

# --- windows ---------------------------------------------------------------
def pkg_id(script):
    m = re.match(r"\d+-([a-z]+)-(.+)$", script)
    return (m.group(2), m.group(1)) if m else (script, "?")

starts = {}
for log in glob.glob(os.path.join(logdir, "blfs-build*.log")):
    for m in re.finditer(r"^== \[\d+/\d+\] (\S+)\s+(\d\d):(\d\d)$", open(log, errors="replace").read(), re.M):
        starts.setdefault(m.group(1), []).append((int(m.group(2)), int(m.group(3))))
exact = {}
tfile = os.path.join(root, "blfs/timings.tsv")
if os.path.exists(tfile):
    for line in open(tfile).read().splitlines()[1:]:
        st, script, t0, t1, secs, res = line.split("\t")[:6]
        if res == "ok":   # ("already built" skips write no timing line)
            exact[script] = (float(t0), float(t1))
# Log birth/last-write times: Python can't read birth time on Linux, so
# they come from `stat -c '%n %W %Y'` (logs-times.txt next to this script's
# output).
births = {}
for line in open(os.path.join(os.path.dirname(out), "logs-times.txt")):
    n, b, mt = line.rsplit(" ", 2)
    births[os.path.basename(n)[:-4]] = (float(b), float(mt))
def last_driver_start(m, t1):
    """The latest "== [n/N] m HH:MM" line in the driver's own logs at or
    before t1, as a time (minute resolution), or None."""
    best = None
    for hh, mm in starts.get(m, []):
        day = dt.datetime.fromtimestamp(t1, utc).replace(hour=hh, minute=mm, second=0, microsecond=0)
        if day.timestamp() > t1 + 60:
            day -= dt.timedelta(days=1)
        if best is None or day.timestamp() > best:
            best = day.timestamp()
    return best

windows = []   # (start, end, id, script)
for d in sorted(glob.glob(os.path.join(root, "blfs/done*"))):
    for m in sorted(os.listdir(d)):
        pid = pkg_id(m)[0]
        if m in births:
            # The log's own times, to the nanosecond. A log is born at a
            # script's first attempt; a later attempt (a retry, or the same
            # script name in a later stage) rewrites it. Its start is then
            # the timing log's (whole seconds, clamped below) or, before
            # that existed, the driver's start line (to the minute); the
            # earlier attempt keeps a window of its own up to the next build,
            # since files it wrote may not have been rewritten.
            t0, t1 = births[m]
            later = None
            if m in exact and exact[m][0] > t0 + 2:
                later = exact[m][0]
            else:
                b = last_driver_start(m, t1)
                if b is not None and b > t0 + 120:
                    later = b
            if later is not None:
                windows.append((t0, later, pid, m + "#earlier"))
                t0 = later
        elif m in exact:
            t0, t1 = exact[m]
        else:
            continue
        windows.append((t0, t1, pid, m))
windows = sorted(set(windows))
# Builds never overlapped. A window holding the start of later ones is a
# retry whose log was born at its first attempt (tesseract failed without
# Leptonica, Leptonica was added and built, tesseract ran again): its last
# attempt began after the builds nested in it, and its first attempt keeps
# the part before them.
changed = True
while changed:
    changed = False
    for i, (s0, e0, p0, m0) in enumerate(windows):
        nested = [w for w in windows[i + 1:] if s0 < w[0] < e0 and w[1] <= e0 and w[3] != m0]
        if nested:
            windows[i] = (max(w[1] for w in nested), e0, p0, m0)
            windows.append((s0, min(w[0] for w in nested), p0, m0 + "#earlier"))
            windows = sorted(set(windows))
            changed = True
            break
# No build starts before the previous one's last log line.
windows = [(max(s, windows[i - 1][1]) if i else s, e, p, m) for i, (s, e, p, m) in enumerate(windows)]
# Builds ran one after another, so the next build's start is a hard end;
# SLACK only covers writes after a log's last line before a pause.
windows = [(s, min(e + SLACK, windows[i + 1][0]) if i + 1 < len(windows) else e + SLACK, p, m)
           for i, (s, e, p, m) in enumerate(windows)]

# --- pacman-owned files ----------------------------------------------------------
owned = {}
# The base system as it was before the desktop layer was packaged (BASE_DB),
# so a rerun still sees which files are the desktop layer's.
BASE_DB = os.environ.get("BASE_DB", os.path.join(root, "var/lib/pacman/local"))
for f in glob.glob(os.path.join(BASE_DB, "*/files")):
    pkg = os.path.basename(os.path.dirname(f))
    sect = None
    for line in open(f, errors="replace").read().splitlines():
        if line.startswith("%"):
            sect = line; continue
        if sect == "%FILES%" and line and not line.endswith("/"):
            owned["/" + line] = pkg

# Files written after the build by pkg/fixups.sh, and whose they are.
MANUAL = {"/etc/ld.so.conf.d/qt6.conf": "qt6", "/etc/ld.so.conf.d/kf6.conf": "kf6-intro"}
# ...and by secureboot/sign.sh: the kernel signed in place stays the
# kernel's; the Secure Boot files are a package of their own.
MANUAL_RE = [(re.compile(r"^/boot/vmlinuz-"), "kernel"),
             (re.compile(r"^/usr/lib/ultimate/secureboot/"), "ultimate-secureboot")]
def manual(rel):
    if rel in MANUAL:
        return MANUAL[rel]
    for rx, pid in MANUAL_RE:
        if rx.match(rel):
            return pid
    return None

# --- walk ---------------------------------------------------------------------------
import bisect
wstarts = [w[0] for w in windows]
def window_of(t):
    i = bisect.bisect_right(wstarts, t) - 1
    if i >= 0:
        s, e, pid, m = windows[i]
        if s <= t < e:
            return pid
    return None

packages, unattributed, overlaps = {}, [], []
skipped = 0
def walk(d):
    global skipped
    try:
        it = list(os.scandir(d))
    except OSError:
        return
    for e in it:
        rel = e.path[len(root):]
        if any(rel == s or rel.startswith(s + "/") for s in SKIP_TREES):
            continue
        try:
            st = os.lstat(e.path)
        except OSError:
            continue
        if stat.S_ISDIR(st.st_mode):
            walk(e.path); continue
        if SKIP_FILES.match(rel) or (stat.S_ISLNK(st.st_mode) and ENABLEMENT.match(rel)):
            skipped += 1; continue
        pid = manual(rel) or window_of(st.st_ctime)
        if rel in owned:
            if pid is not None:
                overlaps.append((rel, owned[rel], pid))
            continue
        if pid is None:
            unattributed.append((rel, int(st.st_ctime)))
        else:
            packages.setdefault(pid, []).append(rel)
walk(root)

json.dump({"packages": packages, "unattributed": unattributed, "overlaps": overlaps,
           "windows": [(s, e, p, m) for s, e, p, m in windows]}, open(out, "w"))
n = sum(len(v) for v in packages.values())
print(f"windows: {len(windows)} builds; files attributed: {n} to {len(packages)} packages")
print(f"skipped generated/account files: {skipped}; unattributed: {len(unattributed)}; "
      f"pacman-owned but rewritten by a BLFS build: {len(overlaps)}")
