#!/bin/bash
# Runs INSIDE the build container (see ../blfs-build.sh). Builds the BLFS
# plan generated by plan-blfs.sh inside the LFS chroot, one package script
# at a time, in order.
#
#   /plan           the BLFS tools' home (scripts in /plan/blfs_root/scripts)
#   /mnt/build_dir  the LFS system being built on
#   /work           this repository's scratch/ directory
#
# State lives in the build tree: /blfs/scripts (the prepared scripts),
# /blfs/done (one marker per finished script), /blfs/logs.
set -euo pipefail
# Exported: the kernfs scripts use $LFS. Unexported, they mounted nothing
# into the chroot and redirections created /dev/null as a regular file.
export LFS=/mnt/build_dir
pacman -Sy --noconfirm --needed wget python >/dev/null 2>&1

# Stage 1 keeps its original paths; later stages get their own
# scripts-N/done-N so their numbering can't collide with stage 1's.
STAGE=${STAGE:-1}
sfx=""; [[ $STAGE == 1 ]] || sfx="-$STAGE"
SCRIPTS=$LFS/blfs/scripts$sfx DONE=$LFS/blfs/done$sfx
PLANNED=/plan/stage-$STAGE; [[ -d $PLANNED ]] || PLANNED=/plan/blfs_root/scripts
EXTRA=/work/blfs/extra$sfx
mkdir -p $SCRIPTS $DONE $LFS/blfs/logs $LFS/sources/blfs
# Steps the planner missed (see each file's comment), slotted in by name.
for s in $EXTRA/*; do
  [[ -f $s ]] || continue
  n=${s##*/}
  [[ -f $SCRIPTS/$n ]] || cp "$s" "$SCRIPTS/$n"
done
# Take the planned scripts; keep ones already prepared so fixes stick.
for s in $PLANNED/*; do
  [[ -f $s ]] || continue    # an empty plan: everything asked for is built
  n=${s##*/}
  [[ -f $SCRIPTS/$n ]] || cp "$s" "$SCRIPTS/$n"
done

# Generic fixes for every script:
#  * extract without restoring upstream owners (rootless Podman can't map
#    ids like less-704's 197609);
#  * no wget in the target: sources are fetched below, outside the chroot.
sed -i 's|tar -xvf |tar --no-same-owner -xvf |' $SCRIPTS/*
# The book adds "your user" to groups (lpadmin for CUPS, netdev for
# NetworkManager) with a placeholder name. There's no user at build time;
# the image and installer add the real user to those groups.
sed -i '/^\(\/usr\/sbin\/\)\?usermod .*\*\*EDITME<username>EDITME\*\*$/d' $SCRIPTS/*
# Scripts planned before targets.conf gained BUILD_SUBDIRS=y.
sed -i 's|^export JH_BUILD_SUBDIRS=""$|export JH_BUILD_SUBDIRS="y"|' $SCRIPTS/*

# The book's commands assume each package is installed once. A retried
# script would stop at "group already exists": make account creation
# idempotent (the account name is the last argument).
for s in $SCRIPTS/*; do
  grep -q '^# ultimate: idempotent accounts$' "$s" && continue
  sed -i '0,/^set -e$/s||set -e\
# ultimate: idempotent accounts\
groupadd() { getent group "${@: -1}" >/dev/null \&\& return 0; command groupadd "$@"; }\
useradd() { getent passwd "${@: -1}" >/dev/null \&\& return 0; command useradd "$@"; }|' "$s"
done

# Per-package fixes: fixes/<name>.sh is run with the script path as $1.
for f in /work/blfs/fixes/*.sh; do
  [[ -f $f ]] || continue
  name=$(basename "$f" .sh)
  for s in $SCRIPTS/*-z-"$name"; do
    [[ -f $s ]] && bash "$f" "$s"
  done
done

# Stage 3's kernel rebuild reads the config from the build tree (the
# chroot can't see /work).
cp /work/kernel/config-7.1.8 $LFS/blfs/kernel-config

echo "== fetching sources"
python3 /work/blfs/fetch.py $SCRIPTS $LFS/sources

# The volume's top directory -- the new system's / -- was created owned by
# uid 1000, and systemd-tmpfiles refuses an "unsafe path transition" from a
# non-root / to root-owned /run. / belongs to root.
chown 0:0 $LFS && chmod 755 $LFS

echo "== mounting the chroot's virtual filesystems"
K=$LFS/jhalfs/kernfs-scripts
# Anything left in the unmounted /dev by an earlier run would hide the
# real device nodes; it is only ever junk.
if ! mountpoint -q $LFS/dev; then find $LFS/dev -mindepth 1 -maxdepth 1 -type f -delete; fi
bash $K/devices.sh >/dev/null
[[ -c $LFS/dev/null ]] || { echo "chroot /dev/null is not a device" >&2; exit 1; }
cp /etc/resolv.conf $LFS/etc/resolv.conf
trap 'bash $K/teardown.sh >/dev/null 2>&1 || true' EXIT

# Every attempt's wall-clock time, kept in the build tree (so it survives
# the container): stage, script, start/end (UTC epoch), seconds, result,
# host cores, and the -j the script asked for. tools/build-timings.sh reads
# it; scratch/ci-build.sh ships it with the build's outputs.
TIMINGS=$LFS/blfs/timings.tsv
[[ -f $TIMINGS ]] || printf 'stage\tscript\tstart\tend\tseconds\tresult\tcores\tjobs\n' > $TIMINGS
jobs_of() {  # the job count a script asks for: its NINJAJOBS or -jN, else all cores
  local j
  j=$(grep -m1 -oE '^export NINJAJOBS=[0-9]+|^export MAKEFLAGS="-j[0-9]+"' "$1" | grep -oE '[0-9]+$|[0-9]+"$' | tr -d '"')
  echo "${j:-$(nproc)}"
}

total=$(ls $SCRIPTS | wc -l)
i=0
for s in $SCRIPTS/*; do
  n=${s##*/}; i=$((i + 1))
  [[ -f $DONE/$n ]] && continue
  # A book package built in any earlier run or stage (under any number:
  # replanning renumbers, and the planner doesn't always see what an earlier
  # stage installed) is not built again. Hand steps (-x-) always run.
  if [[ $n == [0-9]*-z-* ]]; then
    prev=$(ls $LFS/blfs/done*/[0-9]*-z-"${n#*-z-}" 2>/dev/null | head -1 || true)
    if [[ -n $prev ]]; then
      echo "== [$i/$total] $n  already built (${prev#$LFS/blfs/})"
      touch $DONE/$n
      continue
    fi
  fi
  echo "== [$i/$total] $n  $(date -u +%H:%M)"
  t0=$(date +%s.%N)
  if chroot $LFS /usr/bin/env -i HOME=/root TERM=xterm LANG=en_US.UTF-8 \
       PATH=/usr/bin:/usr/sbin bash -e /blfs/scripts$sfx/$n > $LFS/blfs/logs/$n.log 2>&1; then
    t1=$(date +%s.%N)
    printf '%s\t%s\t%s\t%s\t%s\tok\t%s\t%s\n' "$STAGE" "$n" $t0 $t1 $(( ${t1%.*} - ${t0%.*} )) "$(nproc)" "$(jobs_of $s)" >> $TIMINGS
    touch $DONE/$n
  else
    t1=$(date +%s.%N)
    printf '%s\t%s\t%s\t%s\t%s\tfailed\t%s\t%s\n' "$STAGE" "$n" $t0 $t1 $(( ${t1%.*} - ${t0%.*} )) "$(nproc)" "$(jobs_of $s)" >> $TIMINGS
    echo "!! $n failed; log: /blfs/logs/$n.log"
    tail -25 $LFS/blfs/logs/$n.log
    exit 1
  fi
done
echo "== all $total scripts done"
